#!/bin/bash
#PBS -l nodes=1:ppn=48
#PBS -l walltime=72:00:00
#PBS -q bigmem
#PBS -N ml_baselines
#PBS -A loni_bionoi01
#PBS -j oe

module purge
source activate pytorch
cd ~
cd /work/wshi6/deeplearning-data/bionoi_ml_prj/bionoi_ml/
python mlp.py -op control_vs_nucleotide -log_dir ./log_autoencoder_mlp/ > ./log_autoencoder_mlp/mlp_control_vs_nucleotide.log 2>&1
python logistic_regression.py -op control_vs_heme -log_dir ./log_autoencoder_logistic_regression/ > ./log_autoencoder_logistic_regression/lr_control_vs_heme.log 2>&1
python logistic_regression.py -op control_vs_nucleotide -log_dir ./log_autoencoder_logistic_regression/ > ./log_autoencoder_logistic_regression/lr_control_vs_nucleotide.log 2>&1




