#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -q workq
#PBS -N mlp_img
#PBS -A loni_bionoi01
#PBS -j oe

source activate pytorch
cd /work/wshi6/deeplearning-data/bionoi_ml_prj/bionoi_ml/
python mlp_pytorch_img.py -op control_vs_heme  > ./log_mlp_on_img/mlp_img_control_vs_heme.log 2>&1




