#!/bin/bash
#PBS -l nodes=1:ppn=48
#PBS -l walltime=72:00:00
#PBS -q bigmem
#PBS -N mlp
#PBS -A loni_bionoi01
#PBS -j oe

module purge
source activate pytorch
cd ~
cd /work/wshi6/deeplearning-data/bionoi_ml_prj/bionoi_ml/
python mlp.py -op control_vs_heme > ./log/autoencoder_mlp_control_vs_heme.log 2>&1
